sudo: required
dist: trusty
language: python
env:
  - TRAVIS=true
python:
  - "3.5.1"
script:
  - spec unit
  - spec integration
before_install:
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get update
  - sudo apt-get install -qq -y libffi-dev libicu-dev llvm-dev exuberant-ctags neovim
notifications:
  email:
    on_success: change
    on_failure: change
